// Generated by ResEdit 1.6.6
// Copyright (C) 2006-2015
// http://www.resedit.net

HINSTANCE hInst = GetModuleHandle(0);
WNDCLASSEX wcex;
ZeroMemory(&wcex, sizeof wcex);
wcex.cbSize         = sizeof wcex;
wcex.hbrBackground  = (HBRUSH)(COLOR_3DFACE + 1);
wcex.lpszMenuName   = 0;


wcex.style          = CS_HREDRAW | CS_VREDRAW;
wcex.lpfnWndProc    = DefWindowProc;
wcex.hInstance      = hInst;
wcex.hIcon          = LoadIcon(0, (LPCTSTR)IDI_APPLICATION);
wcex.hCursor        = LoadCursor(NULL, IDC_ARROW);
wcex.lpszClassName  = "WndClass1";
RegisterClassEx(&wcex);

HFONT hfont1 = CreateFont(-11, 0, 0, 0, 400, FALSE, FALSE, FALSE, 1, 400, 0, 0, 0, ("Ms Shell Dlg"));
HWND hwnd = CreateWindowEx(, WS_EX_LEFT, ("WndClass")1, ("Dialog"), WS_CAPTION | WS_VISIBLE | WS_POPUP | WS_SYSMENU, 0, 0, 294, 318, 0, 0, hInst, 0);
HWND hCtrl1_0 = CreateWindowEx(0, WC_EDIT, (""), WS_VISIBLE | WS_CHILD | WS_TABSTOP | WS_BORDER | ES_AUTOHSCROLL, 27, 11, 234, 239, hwnd, (HMENU)0, hInst, 0);
SendMessage(hCtrl1_0, WM_SETFONT, (WPARAM), FALSE);
HWND hCtrl1_1 = CreateWindowEx(0, WC_EDIT, (""), WS_VISIBLE | WS_CHILD | WS_TABSTOP | WS_BORDER | ES_AUTOHSCROLL, 27, 258, 234, 23, hwnd, (HMENU)0, hInst, 0);
SendMessage(hCtrl1_1, WM_SETFONT, (WPARAM), FALSE);


