import "./auth/get";
import "./discord/get";
import "./gateway/auth/get";
import "./gateway/callback/get";
import "./gateway/[hwid]/get";
import "./gateway/[hwid]/post";
import "./healthcheck/get";
import "./releases/get";
import "./releases/[platform]/get";
// import "./releases/[platform]/[version]/post";
